name: 3d print
favicon: null
layout_spectrum: 0.9051809890661389
typography_spectrum: 0.2823352571576834
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7197721765842289
  lightness: 0.29783463128842413
  saturation: 0.9114625882357359
  rhythmicContrast: 0.5839734107721597
purpose: []
